.TH file-monitor 1 "July 11, 2012" "version 2.0.0"
.SH NAME
file-monitor \- File viewer that automatically redraws when files change on disk.
.SH SYNOPSIS
.B file-monitor
\-i file_1 [file_2 file_3 file_4 ... file_9]
.SH DESCRIPTION
File Monitor is a cross-platform tool that displays files and
automatically reloads them when they are changed on disk.  This
makes File Viewer a perfect log viewer, or a nice canvas upon
which to monitor changes in visual program output.  
.PP
To begin using File Monitor, either drag a file onto
File Monitor or click the load file button.  File Monitor
allows you to zoom into and navigate files of interest.
Whenever a file is reloaded or closed and opened, all
navigation settings are restored.
.PP
File Monitor supports the display of text, html, svg, and image
file formats.
.PP
For more information on File Monitor, visit:
http://code.google.com/p/file-monitor
.SH OPTIONS
There are no options, only required parameters.
.SH AUTHORS
Mark Turney (markturney (at) gmail.com)
.SH COMMENTS
This man page was hand crafted by Mark Turney.
